### ISSUE TITLE
Multiple tier tokens on wishlist (for Offspec etc) do not show up on prio page

### ISSUE THREAD

**Issue by Jakobud** [thatsmybis/thatsmybis#293] opened 2022-10-19 14:58 UTC
**Describe the bug**
If a character adds the same tier token to their wishlist multiple times (in the case that they need multiple for offspec, etc), when you go set priorities for that item, it only shows them having it on their wishlist a single time, so the list becomes inaccurate.

![image](https://user-images.githubusercontent.com/87356/196727012-19b06d8c-95bd-4368-88f2-1082edbe0257.png)

![image](https://user-images.githubusercontent.com/87356/196727152-b58f9816-fd24-4fd3-b6d5-bdf76dcc5c95.png)

So in this example, this character has a tier item multiple times on their wishlist at positions #3 and #22. But when you go to set the loot prio for that item, it only shows that character having it a single time on their wishlist at #22.

**Expected behavior**
Item prio page should show when a character wishlists an item more than once.

**Comment by markus101** [comment] 2022-10-26 19:35
Ran into the same, but also noticed this is likely a duplicate of https://github.com/thatsmybis/thatsmybis/issues/259 which also includes a bit more context on the related issues with it.

**Comment by Lemmings19** [comment] 2022-11-08 22:21
Correct; closing. Will need to work on this. See #259

**Closed by Lemmings19** 2022-11-08 22:21 UTC
Labels: duplicate

**Comment by Lemmings19** [comment] 2022-11-10 18:37
Duplicates of wishlist items and received items should now be showing on the prio edit page and instance loot page.
